config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             only: [:sessions],
             path: 'admin',
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { sessions: 'devise/sessions' }
  get '/admins/logout' => 'devise/sessions#destroy'
  resources :lists, except: [:destroy]
  resources :schools, except: [:destroy]
  resources :rootboxs, except: [:destroy]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get '/top' => 'homes#top'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
   root "homes#top"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Deviseのサインイン後リダイレクト先をカスタマイズ
  protected

  def after_sign_in_path_for(resource_or_scope)
    lists_path  # ListsController#index のルートヘルパー
  end
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #allow_browser versions: :modern
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/rootboxs_controller.rb
class RootboxsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/rootboxs_helper.rb
module RootboxsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>S

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
    <div class="flash <%= key %>">
      <%= message %>
    </div>
    <% end %>

    <% if admin_signed_in? %>
      <%= button_to "ログアウト", destroy_admin_session_path,
        method: :delete,
        data: { turbo_confirm: "本当にログアウトしますか？" } %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/rootboxs/edit.html.erb
<h1>Rootboxs#edit</h1>
<p>Find me in app/views/rootboxs/edit.html.erb</p>

app/views/rootboxs/index.html.erb
<h1>Rootboxs#index</h1>
<p>Find me in app/views/rootboxs/index.html.erb</p>

app/views/rootboxs/new.html.erb
<h1>Rootboxs#new</h1>
<p>Find me in app/views/rootboxs/new.html.erb</p>

app/views/rootboxs/show.html.erb
<h1>Rootboxs#show</h1>
<p>Find me in app/views/rootboxs/show.html.erb</p>

app/views/schools/edit.html.erb
<h1>Schools#edit</h1>
<p>Find me in app/views/schools/edit.html.erb</p>

app/views/schools/index.html.erb
<h1>Schools#index</h1>
<p>Find me in app/views/schools/index.html.erb</p>

app/views/schools/new.html.erb
<h1>Schools#new</h1>
<p>Find me in app/views/schools/new.html.erb</p>

app/views/schools/show.html.erb
<h1>Schools#show</h1>
<p>Find me in app/views/schools/show.html.erb</p>